name: Gatsby Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with: 
          deploy-branch: 'main'
          access-token: ${{ secrets.ACCESS_TOKEN }}
